version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/envs/dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directories:
      - "/apps/api"
      - "/apps/worker"
    schedule:
      interval: "weekly"