apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demoapp-db
  namespace: demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: demoapp-db
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: demoapp/db
        property: db_host
    - secretKey: DB_NAME
      remoteRef:
        key: demoapp/db
        property: db_name
    - secretKey: DB_USER
      remoteRef:
        key: demoapp/db
        property: db_username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: demoapp/db
        property: db_password