apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- hpa.yaml
images:
- name: api
  newName: ghcr.io/krish10021995/aws-gitops-api
  newTag: 300d5bb194a73fc1aa09aca0c0252802b4cc9e50
