apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- hpa.yaml
images:
- name: api
  newName: ghcr.io/krish10021995/aws-gitops-api
  newTag: 64d72fdffddf0119b698dfb1b76234067a7c747b
