apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- hpa.yaml
- ingress.yaml
images:
- name: web
  newName: ghcr.io/krish10021995/aws-gitops-web
  newTag: 64d72fdffddf0119b698dfb1b76234067a7c747b
