apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-apps
  namespace: argocd
spec:
  description: demo apps deployed by aws-gitops (api, worker, web)
  sourceRepos:
    - https://github.com/Krish10021995/aws-gitops.git
  destinations:
    - namespace: demo
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
  sourceNamespaces:
    - demo
    - argocd